import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Cards from '../components/Cards';
import cardStyles from '../components/Cards.module.css';
import Link from 'next/link';

 function Home({CharacterData}) {
  
  return (
    <>
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <main className={styles.main}>
        <div className={cardStyles.row}>
          {CharacterData.results.map((chareacter) =>
            <Cards 
              imageSrc={chareacter.image}
              name={chareacter.name}
              status={chareacter.status} 
              species={chareacter.species}
              type={chareacter.type}
              gender={chareacter.gender}
              location={chareacter.location.name}
              key={chareacter.id}/>
          )} 
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const CharacterData = await res.json();
  return {
    props: {
      CharacterData,
    },
  }
}


export default Home;